version: '3.8'

services:

  laravel-docker:
    container_name: laravel-docker
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:80"
    volumes:
      - ./laravel-app:/var/www/html
    depends_on:
      - mysql_db

  mysql_db:
    image: mariadb:10.4.27
    container_name: mysql_db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.0
    container_name: phpmyadmin
    ports:
      - "9001:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql_db
